### ISSUE TITLE
Reducers are not pure function

### ISSUE THREAD

**Issue by markerikson** [krzysztofpniak/redux-async-toolkit#1]
You're creating new Dates in your reducers.  That means your reducers are no longer pure functions, and is not the way Redux reducers should work.  You should probably move that to the action side of things, like in the middleware.

**Comment by markerikson** [comment]
Fix title typo

**Comment by krzysztofpniak** [comment]
You are right, I will fix that later today. Thanks for noticing that.

**Comment by krzysztofpniak** [comment]
fixed in 0.1.9
